### ISSUE TITLE
Any plan to release the pre-trained model?

### ISSUE THREAD

**Issue by VVVINCENTJ** [Albert-Ma/COSTA#1]
I'll appreciate it if you can release the pre-trained model. I'd like to fine-tune it on other datasets.

**Comment by Albert-Ma** [comment]
I'll release the pre-trained COSTA model in the next few days. 
The pertaining code may be ready when I'm totally free.

**Comment by Albert-Ma** [comment]
Check out the model [here](https://github.com/Albert-Ma/COSTA#pre-trained-models-in-the-huggingface-)!

**Comment by VVVINCENTJ** [comment]
many thanks!
